//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.Logistics.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentHistory
    {
        public int HistoryID { get; set; }
        public Nullable<System.Guid> ShipmentID { get; set; }
        public string Text { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
