//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.Logistics.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public Shipment()
        {
            this.ShipmentHistories = new HashSet<ShipmentHistory>();
            this.ShipmentReceipients = new HashSet<ShipmentReceipient>();
            this.ShipmentSenders = new HashSet<ShipmentSender>();
        }
    
        public System.Guid ShipmentID { get; set; }
        public string ShipmentAWB { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ActualDeliveryOn { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryOn { get; set; }
        public string Details { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<ShipmentHistory> ShipmentHistories { get; set; }
        public virtual ICollection<ShipmentReceipient> ShipmentReceipients { get; set; }
        public virtual ICollection<ShipmentSender> ShipmentSenders { get; set; }
    }
}
